"""Ed25519 signing/verification, SHA-3-256 hashing, binary Merkle root.

All primitives are deterministic and standards-compliant.

* Signing/verification: Ed25519 per RFC 8032, via the ``cryptography``
  library. Keys generated by ``generate_keypair`` are sourced from the
  OS CSPRNG (``cryptography`` delegates to ``os.urandom``).
* Hashing: SHA-3-256 (FIPS 202). Konnex protocol uses SHA-3
  (https://docs.konnex.world/understand-konnex/protocol-architecture).
* Merkle root: standard binary tree, SHA-3-256. Odd-count levels
  duplicate the last hash (RFC 6962 §2.1 convention). Empty list
  collapses to ``sha3_256(b"")``.

Security notes (audited at Phase 0; revisit in Phase 8 hardening):

* Private key bytes are returned to the caller as immutable ``bytes``.
  Production hardening should keep them inside the TEE simulator and
  never expose them; for Phase 0 this matches the spec's
  ``generate_keypair() -> (priv, pub)`` signature in Section 6.1.
* ``verify`` returns ``False`` for any malformed input — never raises
  — so verifier pipelines (DetVerify Stage 1) can treat all failures
  uniformly. This is fail-secure.
* Signature comparison goes through the ``cryptography`` library's
  Ed25519 verify, which raises ``InvalidSignature`` internally; we
  catch and convert to ``False``. The library's verify is not
  documented as constant-time across all platforms but the secret
  material is the *signer's* private key, not present at verify time,
  so timing leaks here do not expose key bits. Documented per the
  ``constant-time-analysis`` skill.
"""

from __future__ import annotations

import hashlib

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)

from core.config import (
    ED25519_PRIVATE_BYTES,
    ED25519_PUBLIC_BYTES,
    ED25519_SIGNATURE_BYTES,
)


def generate_keypair() -> tuple[bytes, bytes]:
    """Generate a fresh Ed25519 keypair.

    Returns:
        A tuple ``(private_bytes, public_bytes)`` where each element is
        exactly 32 bytes per RFC 8032 §5.1.5.

    Notes:
        Keys come from the OS CSPRNG. Private bytes are caller-owned;
        production code paths (TEE simulator) should retain them only
        inside the secure boundary.
    """
    private = Ed25519PrivateKey.generate()
    private_bytes = private.private_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PrivateFormat.Raw,
        encryption_algorithm=serialization.NoEncryption(),
    )
    public_bytes = private.public_key().public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )
    return private_bytes, public_bytes


def sign(private_bytes: bytes, message: bytes) -> bytes:
    """Produce an Ed25519 signature.

    Args:
        private_bytes: 32-byte raw Ed25519 private key.
        message: Arbitrary message bytes; signed in full (no truncation).

    Returns:
        64-byte Ed25519 signature per RFC 8032 §5.1.6.

    Raises:
        ValueError: If ``private_bytes`` is not exactly 32 bytes.
    """
    if len(private_bytes) != ED25519_PRIVATE_BYTES:
        msg = f"private key must be {ED25519_PRIVATE_BYTES} bytes, " f"got {len(private_bytes)}"
        raise ValueError(msg)
    private = Ed25519PrivateKey.from_private_bytes(private_bytes)
    return private.sign(message)


def verify(public_bytes: bytes, message: bytes, signature: bytes) -> bool:
    """Verify an Ed25519 signature.

    Returns:
        ``True`` iff ``signature`` is a valid Ed25519 signature of
        ``message`` under ``public_bytes``. Returns ``False`` for any
        malformed input — never raises.

    Notes:
        Fail-secure: every failure mode (wrong length, invalid point,
        bad signature) collapses to ``False`` so downstream pipeline
        stages can treat all rejection paths uniformly.

        We additionally reject the canonical all-zero public key. That
        encoding is the curve's identity element, against which the
        all-zero signature trivially satisfies the verification
        equation for any message — a small-subgroup / weak-key class
        that vanilla RFC 8032 verifiers do not exclude. DetVerify
        Stage 1 must never accept such a packet, so we exclude the
        identity point at the wrapper layer.
    """
    if len(public_bytes) != ED25519_PUBLIC_BYTES:
        return False
    if len(signature) != ED25519_SIGNATURE_BYTES:
        return False
    if public_bytes == b"\x00" * ED25519_PUBLIC_BYTES:
        return False
    try:
        public = Ed25519PublicKey.from_public_bytes(public_bytes)
        public.verify(signature, message)
    except (InvalidSignature, ValueError):
        return False
    return True


def sha3_256(data: bytes) -> bytes:
    """Compute SHA-3-256 over ``data``.

    Returns:
        32-byte digest per FIPS 202.
    """
    return hashlib.sha3_256(data).digest()


def merkle_root(leaves: list[bytes]) -> bytes:
    """Compute a binary Merkle root over ``leaves`` using SHA-3-256.

    Convention:
        * Empty input: returns ``sha3_256(b"")``.
        * Odd-count level: the last hash is duplicated and paired with
          itself (RFC 6962 §2.1).

    Args:
        leaves: Ordered list of arbitrary-byte leaves. Order matters;
            the root changes if leaves are reordered.

    Returns:
        32-byte Merkle root.
    """
    if not leaves:
        return sha3_256(b"")

    level: list[bytes] = [sha3_256(leaf) for leaf in leaves]
    while len(level) > 1:
        if len(level) % 2 == 1:
            level.append(level[-1])
        level = [sha3_256(level[i] + level[i + 1]) for i in range(0, len(level), 2)]
    return level[0]
